packages:
  - packages/*

catalog:
  '@better-auth/utils': ^0.3.0
  '@atproto/api': ^0.18.3
  '@fullcalendar/core': ^6.1.19
  '@fullcalendar/daygrid': ^6.1.19
  '@fullcalendar/interaction': ^6.1.19
  '@fullcalendar/list': ^6.1.19
  '@fullcalendar/multimonth': ^6.1.19
  '@fullcalendar/scrollgrid': ^6.1.19
  '@fullcalendar/timegrid': ^6.1.19
  '@fullcalendar/vue3': ^6.1.19
  '@huggingface/transformers': 3.8.0
  '@libsql/client': ^0.15.15
  '@nuxt/content': 3.8.2
  '@nuxt/eslint': latest
  '@nuxt/fonts': ^0.12.1
  '@nuxt/hints': 1.0.0-alpha.1
  '@nuxt/image': 2.0.0
  '@nuxt/scripts': 0.13.0
  '@nuxt/test-utils': 3.20.1
  '@nuxt/ui': 4.2.1
  '@nuxtjs/i18n': ^10.2.1
  '@nuxtjs/seo': ^3.2.2
  '@types/mjml': ^4.7.4
  '@types/three': ^0.181.0
  '@unhead/vue': ^2.0.19
  '@vueuse/core': 14.1.0
  '@vueuse/motion': 3.0.3
  '@vueuse/nuxt': 14.0.0
  axios: ^1.13.2
  better-auth: ^1.3.34
  better-sqlite3: ^12.4.6
  dayjs: ^1.11.19
  drizzle-kit: ^0.31.7
  drizzle-orm: ^0.44.7
  echarts: ^6.0.0
  eslint: ^9.39.1
  fabric: ^6.9.0
  googleapis: 166.0.0
  mjml: ^4.17.1
  nuxt: ^4.2.1
  nuxt-auth-utils: ^0.5.25
  nuxt-file-storage: ^0.3.0
  sass: ^1.94.2
  sharp: ^0.34.5
  three: ^0.181.2
  tsx: 4.20.6
  twitter-api-v2: 1.28.0
  typescript: ^5.9.3
  vue: ^3.5.25
  vue-router: ^4.6.3
  zod: ^4.1.13
  zod-to-json-schema: ^3.25.0
  tailwindcss: 4.1.17
  "nuxt-umami": "^3.2.1"

onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - better-sqlite3
  - onnxruntime-node
  - protobuf
  - protobufjs
  - unrs-resolver
ignoredBuiltDependencies:
- fsevents
- sharp