packages:
  - packages/*

catalog:
  '@better-auth/utils': 0.3.0
  '@atproto/api': 0.18.9
  '@fullcalendar/core': 6.1.20
  '@fullcalendar/daygrid': 6.1.20
  '@fullcalendar/interaction': 6.1.20
  '@fullcalendar/list': 6.1.20
  '@fullcalendar/multimonth': 6.1.20
  '@fullcalendar/scrollgrid': 6.1.20
  '@fullcalendar/timegrid': 6.1.20
  '@fullcalendar/vue3': 6.1.20
  '@huggingface/transformers': 3.8.1
  '@libsql/client': 0.15.15
  '@nuxt/content': 3.10.0
  '@nuxt/eslint': latest
  '@nuxt/fonts': 0.12.1
  '@nuxt/hints': 1.0.0-alpha.1
  '@nuxt/image': 2.0.0
  '@nuxt/scripts': 0.13.2
  '@nuxt/test-utils': 3.21.0
  '@nuxt/ui': 4.3.0
  '@nuxtjs/i18n': 10.2.1
  '@nuxtjs/seo': 3.3.0
  '@types/mjml': 4.7.4
  '@types/three': 0.182.0
  '@unhead/vue': 2.1.1
  '@vueuse/core': 14.1.0
  '@vueuse/motion': 3.0.3
  '@vueuse/nuxt': 14.1.0
  '@ai-sdk/vue': 3.0.5
  axios: 1.13.2
  better-auth: 1.4.9
  better-sqlite3: 12.5.0
  dayjs: 1.11.19
  drizzle-kit: 0.31.8
  drizzle-orm: 0.45.1
  echarts: 6.0.0
  eslint: 9.39.2
  fabric: 7.0.0
  googleapis: 169.0.0
  mjml: 4.18.0
  nuxt: 4.2.2
  nuxt-auth-utils: 0.5.26
  nuxt-file-storage: 0.3.0
  sass: 1.97.0
  sharp: 0.34.5
  three: 0.182.0
  tsx: 4.21.0
  twitter-api-v2: 1.28.0
  typescript: 5.9.3
  vue: 3.5.26
  vue-router: 4.6.4
  zod: 4.2.1
  tailwindcss: 4.1.18
  "nuxt-umami": "3.2.1"
  vitest: 4.0.16

onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - better-sqlite3
  - onnxruntime-node
  - protobuf
  - protobufjs
  - unrs-resolver
ignoredBuiltDependencies:
- fsevents
- sharp
