packages:
  - packages/*

catalog:
  '@atproto/api': 0.19.5
  '@better-auth/utils': 0.4.0
  '@fullcalendar/core': 6.1.20
  '@fullcalendar/daygrid': 6.1.20
  '@fullcalendar/interaction': 6.1.20
  '@fullcalendar/list': 6.1.20
  '@fullcalendar/multimonth': 6.1.20
  '@fullcalendar/scrollgrid': 6.1.20
  '@fullcalendar/timegrid': 6.1.20
  '@fullcalendar/vue3': 6.1.20
  '@huggingface/transformers': 4.0.0
  '@libsql/client': 0.17.2
  '@nuxt/content': 3.12.0
  '@nuxt/eslint': latest
  '@nuxt/fonts': 0.14.0
  '@nuxt/hints': 1.0.2
  '@nuxt/image': 2.0.0
  '@nuxt/scripts': 0.13.2
  '@nuxt/test-utils': 4.0.0
  '@nuxt/ui': 4.6.0
  '@nuxtjs/i18n': 10.2.4
  '@nuxtjs/seo': 5.1.0
  '@playwright/test': 1.58.2
  '@types/mjml': 4.7.4
  '@types/papaparse': 5.5.2
  '@types/three': 0.183.1
  '@unhead/vue': 2.1.12
  '@vitejs/plugin-vue': 6.0.5
  '@vitest/coverage-v8': 4.1.2
  '@vueuse/core': 14.2.1
  '@vueuse/motion': 3.0.3
  '@vueuse/nuxt': 14.2.1
  ai: 6.0.141
  "@ai-sdk/vue": "3.0.141"
  axios: 1.14.0
  better-auth: 1.5.6
  "@better-auth/api-key": 1.5.6
  better-sqlite3: 12.8.0
  cheerio: ^1.2.0
  consola: 3.4.2
  dayjs: 1.11.20
  drizzle-kit: 0.31.10
  drizzle-orm: 0.45.2
  echarts: 6.0.0
  eslint: 10.1.0
  evlog: 2.10.0
  fabric: 7.2.0
  googleapis: 171.4.0
  happy-dom: 20.8.9
  mjml: 4.18.0
  modern-screenshot: 4.6.8
  nuxt: 4.4.2
  nuxt-auth-utils: 0.5.29
  nuxt-file-storage: 0.3.2
  nuxt-umami: 3.2.1
  papaparse: 5.5.3
  sass: 1.98.0
  sharp: 0.34.5
  tailwindcss: 4.2.2
  three: 0.183.2
  tsx: 4.21.0
  twitter-api-v2: 1.29.0
  typescript: 6.0.2
  unhead: 2.1.12
  vitest: 4.1.2
  vue: 3.5.31
  vue-router: 5.0.4
  zod: 4.3.6
  '@comark/nuxt': 0.1.2
  mediabunny: 1.40.1
  idb: 8.0.3
  "wavesurfer.js": 7.12.5

ignoredBuiltDependencies:
  - fsevents
  - sharp

onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - better-sqlite3
  - onnxruntime-node
  - protobuf
  - protobufjs
  - unrs-resolver

