<i18n src="./video.json"></i18n>
<script lang="ts" setup>
const { t } = useI18n()

// Step management
const currentStep = ref(0)
const totalSteps = 4

const steps = computed(() => [
  { label: t('steps.content'), icon: 'i-lucide-file-text' },
  { label: t('steps.script'), icon: 'i-lucide-script' },
  { label: t('steps.metadata'), icon: 'i-lucide-settings-2' },
  { label: t('steps.publish'), icon: 'i-lucide-send' },
])

// Step 1: Content Input
const topic = ref('')
const voiceType = ref('natural')
const inspirationLinks = ref<string[]>([])
const newLink = ref('')
const isGeneratingScript = ref(false)

const voiceOptions = [
  { label: t('step1.voiceNatural'), value: 'natural' },
  { label: t('step1.voiceProfessional'), value: 'professional' },
  { label: t('step1.voiceCasual'), value: 'casual' },
  { label: t('step1.voiceEnergetic'), value: 'energetic' },
  { label: t('step1.voiceStoryteller'), value: 'storyteller' },
]

function addLink() {
  if (newLink.value && newLink.value.trim()) {
    inspirationLinks.value.push(newLink.value.trim())
    newLink.value = ''
  }
}

function removeLink(index: number) {
  inspirationLinks.value.splice(index, 1)
}

async function onGenerateScript() {
  if (!topic.value.trim()) return
  isGeneratingScript.value = true
  // TODO: Backend integration
  await new Promise(resolve => setTimeout(resolve, 1500))
  scriptContent.value = `Here's a generated script about "${topic.value}"...\n\nThis is a placeholder script that will be generated by the AI backend.\n\nThe hook will grab attention in the first 3 seconds.\nThen we deliver the core value proposition.\nFollowed by key points that support the main message.\nEnd with a strong call to action.`
  isGeneratingScript.value = false
  currentStep.value = 1
}

// Step 2: Script Editor
const scriptContent = ref('')
const selectedHook = ref('curiosity')
const isCheckingHealth = ref(false)
const healthResult = ref<{
  score: number
  metrics: { hookStrength: number; relevance: number; retention: number }
  feedback: string
  improvedScript: string
  alternativeVersions: { hookName: string; retention: number; script: string }[]
} | null>(null)

const hookOptions = [
  { label: t('step2.hookCuriosity'), value: 'curiosity' },
  { label: t('step2.hookNegative'), value: 'negative' },
  { label: t('step2.hookContrarian'), value: 'contrarian' },
  { label: t('step2.hookListicle'), value: 'listicle' },
]

async function onCheckHealth() {
  if (!scriptContent.value.trim()) return
  isCheckingHealth.value = true
  // TODO: Backend integration
  await new Promise(resolve => setTimeout(resolve, 1500))
  healthResult.value = {
    score: 78,
    metrics: { hookStrength: 82, relevance: 75, retention: 74 },
    feedback: 'The hook is strong but could be more specific. Consider opening with a relatable pain point to improve retention.',
    improvedScript: 'Here is an improved version of your script with better pacing and a stronger hook...\n\n[Improved script content will be generated by AI]',
    alternativeVersions: [
      { hookName: 'The Curiosity Gap', retention: 85, script: 'Alternative script using a curiosity gap approach...' },
      { hookName: 'The Contrarian', retention: 80, script: 'Alternative contrarian take on the same topic...' },
    ],
  }
  isCheckingHealth.value = false
}

function acceptImprovedScript(script: string) {
  scriptContent.value = script
  healthResult.value = null
}

function loadHookVariation(hook: string) {
  selectedHook.value = hook
  // TODO: Backend integration - regenerate script with selected hook
}

// Scene-based media (placeholder)
const scenes = ref<{ text: string; media: string[]; voiceOverride: string | null }[]>([])

function addScene() {
  scenes.value.push({ text: '', media: [], voiceOverride: null })
}

function removeScene(index: number) {
  scenes.value.splice(index, 1)
}

// Step 3: Subtitle & Metadata
const subtitleFont = ref('inter')
const subtitleSize = ref(36)
const subtitlePosition = ref('bottom')
const subtitleColor = ref('white')
const subtitleBg = ref(true)
const aspectRatio = ref<'16:9' | '9:16' | '1:1'>('16:9')
const postTitle = ref('')
const seoDescription = ref('')
const socialPost = ref('')
const isGeneratingVideo = ref(false)

const fontOptions = [
  { label: t('step3.fontModern'), value: 'inter' },
  { label: t('step3.fontClassic'), value: 'serif' },
  { label: t('step3.fontBold'), value: 'montserrat' },
  { label: t('step3.fontPlayful'), value: 'poppins' },
]

const positionOptions = [
  { label: t('step3.posBottom'), value: 'bottom' },
  { label: t('step3.posMiddle'), value: 'middle' },
  { label: t('step3.posTop'), value: 'top' },
]

const colorOptions = [
  { label: 'White', value: 'white', class: 'bg-white' },
  { label: 'Yellow', value: 'yellow', class: 'bg-yellow-400' },
  { label: 'Cyan', value: 'cyan', class: 'bg-cyan-400' },
  { label: 'Green', value: 'green', class: 'bg-green-400' },
  { label: 'Pink', value: 'pink', class: 'bg-pink-400' },
]

async function onGenerateVideo() {
  if (!postTitle.value.trim()) return
  isGeneratingVideo.value = true
  // TODO: Backend integration
  await new Promise(resolve => setTimeout(resolve, 2000))
  videoPreviewUrl.value = '/placeholder-video.mp4'
  isGeneratingVideo.value = false
  currentStep.value = 3
}

// Step 4: Review & Publish
const videoPreviewUrl = ref<string | null>(null)
const bgMusic = ref('none')
const musicVolume = ref(30)
const voiceVolume = ref(80)
const thumbnail = ref<string | null>(null)
const selectedPlatforms = ref<string[]>([])
const scheduleOption = ref<'now' | 'later'>('now')
const scheduledDate = ref('')
const scheduledTime = ref('')
const isPublishing = ref(false)

const musicOptions = [
  { label: t('step4.bgMusicNone'), value: 'none' },
  { label: t('step4.bgMusicCorporate'), value: 'corporate' },
  { label: t('step4.bgMusicUpbeat'), value: 'upbeat' },
  { label: t('step4.bgMusicCinematic'), value: 'cinematic' },
  { label: t('step4.bgMusicLofi'), value: 'lofi' },
]

const platformOptions = [
  { label: 'YouTube', value: 'youtube', icon: 'i-lucide-film' },
  { label: 'TikTok', value: 'tiktok', icon: 'i-lucide-music' },
  { label: 'Instagram', value: 'instagram', icon: 'i-lucide-camera' },
  { label: 'Facebook', value: 'facebook', icon: 'i-lucide-message-square' },
  { label: 'LinkedIn', value: 'linkedin', icon: 'i-lucide-briefcase' },
  { label: 'X / Twitter', value: 'twitter', icon: 'i-lucide-hash' },
  { label: 'Bluesky', value: 'bluesky', icon: 'i-lucide-cloud' },
  { label: 'Threads', value: 'threads', icon: 'i-lucide-at-sign' },
]

function togglePlatform(platform: string) {
  const idx = selectedPlatforms.value.indexOf(platform)
  if (idx >= 0) {
    selectedPlatforms.value.splice(idx, 1)
  } else {
    selectedPlatforms.value.push(platform)
  }
}

async function onPublish() {
  if (selectedPlatforms.value.length === 0) return
  isPublishing.value = true
  // TODO: Backend integration
  await new Promise(resolve => setTimeout(resolve, 2000))
  isPublishing.value = false
}

// Navigation
const isSaving = ref(false)

const canProceed = computed(() => {
  switch (currentStep.value) {
    case 0: return !!topic.value.trim()
    case 1: return !!scriptContent.value.trim()
    case 2: return !!postTitle.value.trim()
    case 3: return selectedPlatforms.value.length > 0
    default: return false
  }
})

function nextStep() {
  if (currentStep.value < totalSteps - 1 && canProceed.value) {
    currentStep.value++
  }
}

function prevStep() {
  if (currentStep.value > 0) {
    currentStep.value--
  }
}

async function onSaveDraft() {
  isSaving.value = true
  await new Promise(resolve => setTimeout(resolve, 800))
  isSaving.value = false
}

function handleThumbnailUpload() {
  // TODO: Open media gallery or file picker
  thumbnail.value = '/placeholder-thumbnail.jpg'
}

useHead({
  title: t('title'),
  meta: [
    { name: 'description', content: t('subtitle') },
  ],
})
</script>

<template>
  <div class="container mx-auto py-6 space-y-8">
    <BasePageHeader :title="t('title')" :description="t('subtitle')">
      <template #actions>
        <UButton :loading="isSaving" icon="i-lucide-save" color="neutral" variant="outline" @click="onSaveDraft">
          {{ t('navigation.saveDraft') }}
        </UButton>
      </template>
    </BasePageHeader>

    <!-- Step Indicator -->
    <div class="w-full">
      <div class="flex items-center justify-between max-w-3xl mx-auto">
        <template v-for="(step, idx) in steps" :key="idx">
          <div class="flex items-center">
            <button
              :class="[
                'flex items-center gap-2 px-3 py-2 rounded-lg transition-all duration-300',
                currentStep === idx
                  ? 'bg-primary/10 text-primary'
                  : idx < currentStep
                    ? 'text-primary/60 hover:text-primary/80'
                    : 'text-muted-foreground/40 hover:text-muted-foreground/60',
              ]"
              :disabled="idx > currentStep"
              @click="currentStep = idx"
            >
              <div
                :class="[
                  'w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold transition-all duration-300',
                  currentStep === idx
                    ? 'bg-primary text-primary-foreground shadow-lg shadow-primary/25'
                    : idx < currentStep
                      ? 'bg-primary/20 text-primary'
                      : 'bg-muted text-muted-foreground',
                ]"
              >
                <UIcon v-if="idx < currentStep" name="i-lucide-check" class="w-4 h-4" />
                <span v-else>{{ idx + 1 }}</span>
              </div>
              <span class="hidden sm:block text-xs font-medium">{{ step.label }}</span>
            </button>
          </div>
          <div
            v-if="idx < totalSteps - 1"
            :class="[
              'flex-1 h-px mx-2 transition-all duration-500',
              idx < currentStep ? 'bg-primary/40' : 'bg-muted',
            ]"
          />
        </template>
      </div>
    </div>

    <!-- Step Content -->
    <div class="max-w-4xl mx-auto">
      <!-- Step 1: Content Input -->
      <div v-if="currentStep === 0" class="space-y-8">
        <div class="text-center space-y-2">
          <h2 class="text-2xl font-bold">{{ t('step1.title') }}</h2>
          <p class="text-muted-foreground text-sm">{{ t('step1.description') }}</p>
        </div>

        <UCard>
          <div class="space-y-6 p-2">
            <div class="space-y-2">
              <label class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                {{ t('step1.topicLabel') }}
              </label>
              <UTextarea
                v-model="topic"
                :placeholder="t('step1.topicPlaceholder')"
                :rows="4"
                block
                variant="subtle"
                class="font-mono leading-relaxed w-full"
              />
            </div>

            <div class="space-y-2">
              <label class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                {{ t('step1.voiceLabel') }}
              </label>
              <USelect
                v-model="voiceType"
                :items="voiceOptions"
                block
              />
            </div>

            <div class="space-y-3">
              <label class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                {{ t('step1.linksLabel') }}
              </label>
              <div class="flex gap-2">
                <UInput
                  v-model="newLink"
                  :placeholder="t('step1.linksPlaceholder')"
                  block
                  class="flex-1"
                  @keydown.enter="addLink"
                />
                <UButton color="neutral" variant="outline" :disabled="!newLink.trim()" @click="addLink">
                  {{ t('step1.addLink') }}
                </UButton>
              </div>
              <TransitionGroup name="list" tag="div" class="space-y-2">
                <div
                  v-for="(link, idx) in inspirationLinks"
                  :key="idx"
                  class="flex items-center gap-2 bg-muted/50 rounded-lg px-3 py-2 text-sm"
                >
                  <UIcon name="i-lucide-link" class="w-4 h-4 text-muted-foreground shrink-0" />
                  <span class="truncate flex-1 font-mono text-xs">{{ link }}</span>
                  <UButton
                    color="neutral"
                    variant="ghost"
                    size="xs"
                    square
                    icon="i-lucide-x"
                    @click="removeLink(idx)"
                  />
                </div>
              </TransitionGroup>
            </div>

            <UButton
              :loading="isGeneratingScript"
              :disabled="!topic.trim()"
              block
              size="lg"
              color="primary"
              icon="i-lucide-wand-sparkles"
              @click="onGenerateScript"
            >
              {{ isGeneratingScript ? t('step1.generating') : t('step1.generateScript') }}
            </UButton>
          </div>
        </UCard>
      </div>

      <!-- Step 2: Script Editor -->
      <div v-if="currentStep === 1" class="space-y-8">
        <div class="text-center space-y-2">
          <h2 class="text-2xl font-bold">{{ t('step2.title') }}</h2>
          <p class="text-muted-foreground text-sm">{{ t('step2.description') }}</p>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <div class="lg:col-span-2 space-y-6">
            <UCard>
              <div class="space-y-4 p-2">
                <div class="flex items-center justify-between">
                  <label class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                    {{ t('step2.scriptLabel') }}
                  </label>
                  <span class="text-xs font-mono text-muted-foreground">{{ scriptContent.length }} chars</span>
                </div>
                <UTextarea
                  v-model="scriptContent"
                  :placeholder="t('step2.scriptPlaceholder')"
                  :rows="14"
                  block
                  variant="subtle"
                  class="font-mono leading-relaxed w-full"
                />
              </div>
            </UCard>

            <!-- Health Results -->
            <Transition name="fade">
              <UCard v-if="healthResult" class="border-primary/20">
                <template #header>
                  <div class="flex items-center justify-between">
                    <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                      {{ t('step2.healthScore') }}
                    </h3>
                    <div class="flex items-center gap-2">
                      <span class="text-2xl font-bold text-primary">{{ healthResult.score }}</span>
                      <span class="text-xs text-muted-foreground">/100</span>
                    </div>
                  </div>
                </template>

                <div class="space-y-4 py-2">
                  <div class="space-y-2">
                    <div class="flex justify-between text-xs font-mono">
                      <span class="text-muted-foreground">{{ t('step2.hookStrength') }}</span>
                      <span>{{ healthResult.metrics.hookStrength }}%</span>
                    </div>
                    <UProgress :value="healthResult.metrics.hookStrength" size="xs" color="primary" />
                  </div>
                  <div class="space-y-2">
                    <div class="flex justify-between text-xs font-mono">
                      <span class="text-muted-foreground">{{ t('step2.relevance') }}</span>
                      <span>{{ healthResult.metrics.relevance }}%</span>
                    </div>
                    <UProgress :value="healthResult.metrics.relevance" size="xs" color="primary" />
                  </div>
                  <div class="space-y-2">
                    <div class="flex justify-between text-xs font-mono">
                      <span class="text-muted-foreground">{{ t('step2.retention') }}</span>
                      <span>{{ healthResult.metrics.retention }}%</span>
                    </div>
                    <UProgress :value="healthResult.metrics.retention" size="xs" color="primary" />
                  </div>
                </div>

                <div class="mt-6 space-y-4">
                  <div>
                    <h4 class="text-xs font-mono text-muted-foreground uppercase tracking-wider mb-2">
                      {{ t('step2.feedback') }}
                    </h4>
                    <p class="text-sm border-l-2 border-border pl-4">{{ healthResult.feedback }}</p>
                  </div>

                  <div>
                    <h4 class="text-xs font-mono text-muted-foreground uppercase tracking-wider mb-2">
                      {{ t('step2.improvedScript') }}
                    </h4>
                    <div class="bg-muted p-4 rounded-lg text-xs font-mono whitespace-pre-wrap leading-relaxed">
                      {{ healthResult.improvedScript }}
                    </div>
                    <UButton
                      block
                      color="neutral"
                      variant="soft"
                      size="sm"
                      class="mt-2"
                      @click="acceptImprovedScript(healthResult!.improvedScript)"
                    >
                      {{ t('step2.acceptScript') }}
                    </UButton>
                  </div>

                  <div v-if="healthResult.alternativeVersions.length" class="space-y-4 pt-4 border-t border-border">
                    <h4 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                      {{ t('step2.alternativeVersions') }}
                    </h4>
                    <div
                      v-for="(alt, idx) in healthResult.alternativeVersions"
                      :key="idx"
                      class="bg-muted/50 rounded-lg p-4 space-y-3"
                    >
                      <div class="flex items-center justify-between">
                        <h5 class="font-bold text-sm">{{ alt.hookName }}</h5>
                        <div class="text-right">
                          <div class="text-[10px] font-mono text-muted-foreground uppercase">Retention</div>
                          <div class="font-mono font-bold text-sm text-primary">{{ alt.retention }}%</div>
                        </div>
                      </div>
                      <div class="bg-background rounded-lg p-3 text-xs font-mono whitespace-pre-wrap leading-relaxed">
                        {{ alt.script }}
                      </div>
                      <UButton
                        block
                        size="xs"
                        color="neutral"
                        variant="outline"
                        @click="acceptImprovedScript(alt.script)"
                      >
                        {{ t('step2.useThisVersion') }}
                      </UButton>
                    </div>
                  </div>
                </div>
              </UCard>
            </Transition>
          </div>

          <div class="space-y-4">
            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step2.hookLabel') }}
                </h3>
              </template>
              <div class="space-y-2 p-1">
                <UButton
                  v-for="hook in hookOptions"
                  :key="hook.value"
                  :variant="selectedHook === hook.value ? 'soft' : 'outline'"
                  color="neutral"
                  block
                  size="sm"
                  @click="loadHookVariation(hook.value)"
                >
                  {{ hook.label }}
                </UButton>
              </div>
            </UCard>

            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">AI Actions</h3>
              </template>
              <div class="space-y-2 p-1">
                <UButton
                  :loading="isCheckingHealth"
                  :disabled="!scriptContent.trim()"
                  block
                  color="neutral"
                  variant="outline"
                  size="sm"
                  icon="i-lucide-heart-pulse"
                  @click="onCheckHealth"
                >
                  {{ isCheckingHealth ? t('step2.checkingHealth') : t('step2.checkHealth') }}
                </UButton>
                <UButton
                  block
                  color="neutral"
                  variant="outline"
                  size="sm"
                  icon="i-lucide-iteration-ccw"
                  :disabled="!scriptContent.trim()"
                >
                  {{ t('step2.hookVariations') }}
                </UButton>
                <UButton
                  block
                  color="neutral"
                  variant="outline"
                  size="sm"
                  icon="i-lucide-check-circle"
                  :disabled="!scriptContent.trim()"
                >
                  {{ t('step2.valueCheck') }}
                </UButton>
                <UButton
                  block
                  color="neutral"
                  variant="outline"
                  size="sm"
                  icon="i-lucide-thumbs-up"
                  :disabled="!scriptContent.trim()"
                >
                  {{ t('step2.videoLikeCheck') }}
                </UButton>
                <UButton
                  block
                  color="neutral"
                  variant="outline"
                  size="sm"
                  icon="i-lucide-refresh-cw"
                  :disabled="!scriptContent.trim()"
                >
                  {{ t('step2.refineScript') }}
                </UButton>
              </div>
            </UCard>

            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step2.mediaLabel') }}
                </h3>
              </template>
              <div class="space-y-3 p-1">
                <div v-for="(scene, idx) in scenes" :key="idx" class="bg-muted/30 rounded-lg p-3 space-y-2">
                  <div class="flex items-center justify-between">
                    <span class="text-xs font-mono text-muted-foreground">Scene {{ idx + 1 }}</span>
                    <UButton color="neutral" variant="ghost" size="xs" square icon="i-lucide-x" @click="removeScene(idx)" />
                  </div>
                  <p class="text-xs text-muted-foreground line-clamp-2">{{ scene.text || 'No text assigned' }}</p>
                  <UButton color="neutral" variant="outline" size="xs" block icon="i-lucide-image">
                    Select Media
                  </UButton>
                </div>
                <UButton color="neutral" variant="soft" size="sm" block icon="i-lucide-plus" @click="addScene">
                  {{ t('step2.mediaAddScene') }}
                </UButton>
              </div>
            </UCard>
          </div>
        </div>
      </div>

      <!-- Step 3: Subtitle & Metadata -->
      <div v-if="currentStep === 2" class="space-y-8">
        <div class="text-center space-y-2">
          <h2 class="text-2xl font-bold">{{ t('step3.title') }}</h2>
          <p class="text-muted-foreground text-sm">{{ t('step3.description') }}</p>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <div class="space-y-6">
            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step3.subtitleStyle') }}
                </h3>
              </template>
              <div class="space-y-5 p-2">
                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step3.fontFamily') }}</label>
                  <USelect v-model="subtitleFont" :items="fontOptions" block />
                </div>

                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step3.fontSize') }}</label>
                  <div class="flex items-center gap-3">
                    <USlider v-model="subtitleSize" :min="20" :max="72" :step="2" color="primary" class="flex-1" />
                    <span class="text-xs font-mono w-8 text-right">{{ subtitleSize }}</span>
                  </div>
                </div>

                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step3.position') }}</label>
                  <div class="grid grid-cols-3 gap-2">
                    <UButton
                      v-for="pos in positionOptions"
                      :key="pos.value"
                      :variant="subtitlePosition === pos.value ? 'soft' : 'outline'"
                      color="neutral"
                      size="sm"
                      @click="subtitlePosition = pos.value"
                    >
                      {{ pos.label }}
                    </UButton>
                  </div>
                </div>

                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step3.color') }}</label>
                  <div class="flex gap-2">
                    <button
                      v-for="c in colorOptions"
                      :key="c.value"
                      :class="[
                        'w-8 h-8 rounded-full border-2 transition-all',
                        subtitleColor === c.value ? 'border-primary scale-110' : 'border-transparent',
                        c.class,
                      ]"
                      @click="subtitleColor = c.value"
                    />
                  </div>
                </div>

                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step3.bgLabel') }}</label>
                  <div class="flex gap-2">
                    <UButton
                      :variant="subtitleBg ? 'soft' : 'outline'"
                      color="neutral"
                      size="sm"
                      @click="subtitleBg = true"
                    >
                      {{ t('step3.bgEnabled') }}
                    </UButton>
                    <UButton
                      :variant="!subtitleBg ? 'soft' : 'outline'"
                      color="neutral"
                      size="sm"
                      @click="subtitleBg = false"
                    >
                      {{ t('step3.bgDisabled') }}
                    </UButton>
                  </div>
                </div>
              </div>
            </UCard>

            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step3.videoFormat') }}
                </h3>
              </template>
              <div class="grid grid-cols-3 gap-3 p-2">
                <button
                  v-for="ratio in ([{ value: '16:9', label: t('step3.format16_9') }, { value: '9:16', label: t('step3.format9_16') }, { value: '1:1', label: t('step3.format1_1') }] as const)"
                  :key="ratio.value"
                  :class="[
                    'flex flex-col items-center gap-2 p-4 rounded-xl border-2 transition-all',
                    aspectRatio === ratio.value
                      ? 'border-primary bg-primary/5'
                      : 'border-muted hover:border-muted-foreground/20',
                  ]"
                  @click="aspectRatio = ratio.value"
                >
                  <div
                    :class="[
                      'rounded-lg border-2 bg-muted/50 transition-all',
                      ratio.value === '16:9' ? 'w-16 aspect-video' : '',
                      ratio.value === '9:16' ? 'w-10 aspect-[9/16]' : '',
                      ratio.value === '1:1' ? 'w-12 aspect-square' : '',
                      aspectRatio === ratio.value ? 'border-primary' : 'border-muted',
                    ]"
                  />
                  <span class="text-xs font-medium">{{ ratio.value }}</span>
                  <span class="text-[10px] text-muted-foreground">{{ ratio.label }}</span>
                </button>
              </div>
            </UCard>
          </div>

          <div class="space-y-6">
            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step3.postMetadata') }}
                </h3>
              </template>
              <div class="space-y-5 p-2">
                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step3.postTitle') }}</label>
                  <UInput v-model="postTitle" :placeholder="t('step3.titlePlaceholder')" block />
                </div>

                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step3.seoDescription') }}</label>
                  <UTextarea
                    v-model="seoDescription"
                    :placeholder="t('step3.seoPlaceholder')"
                    :rows="3"
                    block
                    variant="subtle"
                  />
                </div>

                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step3.socialPost') }}</label>
                  <UTextarea
                    v-model="socialPost"
                    :placeholder="t('step3.socialPostPlaceholder')"
                    :rows="5"
                    block
                    variant="subtle"
                  />
                </div>
              </div>
            </UCard>

            <UButton
              :loading="isGeneratingVideo"
              :disabled="!postTitle.trim()"
              block
              size="xl"
              color="primary"
              icon="i-lucide-video"
              class="py-6 text-lg font-bold"
              @click="onGenerateVideo"
            >
              <UIcon name="i-lucide-sparkles" class="mr-2" />
              {{ isGeneratingVideo ? t('step3.generatingVideo') : t('step3.generateVideo') }}
            </UButton>
          </div>
        </div>
      </div>

      <!-- Step 4: Review & Publish -->
      <div v-if="currentStep === 3" class="space-y-8">
        <div class="text-center space-y-2">
          <h2 class="text-2xl font-bold">{{ t('step4.title') }}</h2>
          <p class="text-muted-foreground text-sm">{{ t('step4.description') }}</p>
        </div>

        <div class="grid grid-cols-1 lg:grid-cols-5 gap-6">
          <div class="lg:col-span-3 space-y-6">
            <!-- Video Preview -->
            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step4.preview') }}
                </h3>
              </template>
              <div
                :class="[
                  'bg-neutral-900 rounded-xl overflow-hidden mx-auto',
                  aspectRatio === '16:9' ? 'w-full aspect-video' : '',
                  aspectRatio === '9:16' ? 'w-2/3 aspect-[9/16]' : '',
                  aspectRatio === '1:1' ? 'w-2/3 aspect-square' : '',
                ]"
              >
                <div v-if="videoPreviewUrl" class="w-full h-full flex items-center justify-center bg-neutral-900">
                  <div class="text-center space-y-3">
                    <UIcon name="i-lucide-video" class="text-5xl text-muted-foreground" />
                    <p class="text-xs text-muted-foreground font-mono">Video preview will appear here</p>
                  </div>
                </div>
                <div v-else class="w-full h-full flex items-center justify-center">
                  <div class="text-center space-y-3">
                    <UIcon name="i-lucide-clapperboard" class="text-5xl text-muted-foreground" />
                    <p class="text-sm text-muted-foreground">{{ t('step4.noVideo') }}</p>
                  </div>
                </div>
              </div>
            </UCard>

            <!-- Audio Settings -->
            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step4.audio') }}
                </h3>
              </template>
              <div class="space-y-5 p-2">
                <div class="space-y-2">
                  <label class="text-xs font-mono text-muted-foreground">{{ t('step4.bgMusic') }}</label>
                  <USelect v-model="bgMusic" :items="musicOptions" block />
                </div>
                <div v-if="bgMusic !== 'none'" class="space-y-2">
                  <div class="flex justify-between text-xs font-mono">
                    <span class="text-muted-foreground">{{ t('step4.musicVolume') }}</span>
                    <span>{{ musicVolume }}%</span>
                  </div>
                  <USlider v-model="musicVolume" :min="0" :max="100" color="primary" />
                </div>
                <div class="space-y-2">
                  <div class="flex justify-between text-xs font-mono">
                    <span class="text-muted-foreground">{{ t('step4.voiceVolume') }}</span>
                    <span>{{ voiceVolume }}%</span>
                  </div>
                  <USlider v-model="voiceVolume" :min="0" :max="100" color="primary" />
                </div>
              </div>
            </UCard>
          </div>

          <div class="lg:col-span-2 space-y-6">
            <!-- Thumbnail -->
            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step4.thumbnail') }}
                </h3>
              </template>
              <div class="p-2">
                <button
                  class="w-full aspect-video rounded-xl border-2 border-dashed border-muted hover:border-muted-foreground/30 transition-colors flex flex-col items-center justify-center gap-2 bg-muted/20"
                  @click="handleThumbnailUpload"
                >
                  <template v-if="thumbnail">
                    <div class="w-full h-full bg-muted rounded-lg flex items-center justify-center">
                      <span class="text-xs text-muted-foreground font-mono">{{ t('step4.changeThumbnail') }}</span>
                    </div>
                  </template>
                  <template v-else>
                    <UIcon name="i-lucide-image-plus" class="text-3xl text-muted-foreground" />
                    <span class="text-xs text-muted-foreground font-mono">{{ t('step4.thumbnailPlaceholder') }}</span>
                  </template>
                </button>
              </div>
            </UCard>

            <!-- Platforms -->
            <UCard>
              <template #header>
                <div class="flex items-center justify-between">
                  <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                    {{ t('step4.platforms') }}
                  </h3>
                  <span v-if="selectedPlatforms.length" class="text-xs font-mono text-primary">
                    {{ selectedPlatforms.length }} selected
                  </span>
                </div>
              </template>
              <div class="space-y-1 p-1">
                <button
                  v-for="platform in platformOptions"
                  :key="platform.value"
                  :class="[
                    'w-full flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm transition-all',
                    selectedPlatforms.includes(platform.value)
                      ? 'bg-primary/10 text-primary'
                      : 'hover:bg-muted/50 text-muted-foreground hover:text-foreground',
                  ]"
                  @click="togglePlatform(platform.value)"
                >
                  <div
                    :class="[
                      'w-5 h-5 rounded border-2 flex items-center justify-center transition-all',
                      selectedPlatforms.includes(platform.value)
                        ? 'bg-primary border-primary'
                        : 'border-muted-foreground/30',
                    ]"
                  >
                    <UIcon v-if="selectedPlatforms.includes(platform.value)" name="i-lucide-check" class="w-3 h-3 text-primary-foreground" />
                  </div>
                  <UIcon :name="platform.icon" class="w-4 h-4 shrink-0" />
                  <span>{{ platform.label }}</span>
                </button>
              </div>
            </UCard>

            <!-- Schedule -->
            <UCard>
              <template #header>
                <h3 class="text-xs font-mono text-muted-foreground uppercase tracking-wider">
                  {{ t('step4.schedule') }}
                </h3>
              </template>
              <div class="space-y-4 p-2">
                <div class="flex gap-2">
                  <UButton
                    :variant="scheduleOption === 'now' ? 'soft' : 'outline'"
                    color="neutral"
                    block
                    size="sm"
                    @click="scheduleOption = 'now'"
                  >
                    {{ t('step4.scheduleNow') }}
                  </UButton>
                  <UButton
                    :variant="scheduleOption === 'later' ? 'soft' : 'outline'"
                    color="neutral"
                    block
                    size="sm"
                    @click="scheduleOption = 'later'"
                  >
                    {{ t('step4.scheduleLater') }}
                  </UButton>
                </div>
                <div v-if="scheduleOption === 'later'" class="grid grid-cols-2 gap-3">
                  <div class="space-y-1">
                    <label class="text-[10px] font-mono text-muted-foreground uppercase">{{ t('step4.date') }}</label>
                    <UInput v-model="scheduledDate" type="date" block size="sm" />
                  </div>
                  <div class="space-y-1">
                    <label class="text-[10px] font-mono text-muted-foreground uppercase">{{ t('step4.time') }}</label>
                    <UInput v-model="scheduledTime" type="time" block size="sm" />
                  </div>
                </div>
              </div>
            </UCard>

            <UButton
              :loading="isPublishing"
              :disabled="selectedPlatforms.length === 0"
              block
              size="xl"
              color="primary"
              class="py-6 text-lg font-bold"
              @click="onPublish"
            >
              <UIcon name="i-lucide-send" class="mr-2" />
              {{ isPublishing ? t('step4.publishing') : t('step4.publish') }}
            </UButton>
          </div>
        </div>
      </div>

      <!-- Navigation -->
      <div class="flex items-center justify-between pt-4 border-t border-border">
        <UButton
          v-if="currentStep > 0"
          color="neutral"
          variant="outline"
          icon="i-lucide-arrow-left"
          @click="prevStep"
        >
          {{ t('navigation.back') }}
        </UButton>
        <div v-else />

        <UButton
          v-if="currentStep < totalSteps - 1"
          color="primary"
          :disabled="!canProceed"
          icon="i-lucide-arrow-right"
          trailing
          @click="nextStep"
        >
          {{ t('navigation.next') }}
        </UButton>
      </div>
    </div>
  </div>
</template>

<style scoped>
.fade-enter-active,
.fade-leave-active {
  transition: all 0.3s ease;
}

.fade-enter-from,
.fade-leave-to {
  opacity: 0;
  transform: translateY(10px);
}

.list-enter-active,
.list-leave-active {
  transition: all 0.3s ease;
}

.list-enter-from,
.list-leave-to {
  opacity: 0;
  transform: translateX(-10px);
}
</style>
